version: '3.8'

# 개발 환경용 Docker Compose 설정
services:
  # PostgreSQL 데이터베이스 (개발용)
  db:
    image: postgres:15-alpine
    container_name: studymate-db-dev
    environment:
      POSTGRES_DB: studymate_dev
      POSTGRES_USER: studymate
      POSTGRES_PASSWORD: dev123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # 포트 충돌 방지
    restart: unless-stopped

  # Redis 캐시 (개발용)
  redis:
    image: redis:7-alpine
    container_name: studymate-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"  # 포트 충돌 방지
    restart: unless-stopped

  # StudyMate API (개발용)
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: studymate-api-dev
    environment:
      - DJANGO_SETTINGS_MODULE=studymate_api.settings
      - DEBUG=True
      - ENVIRONMENT=development
      - SECRET_KEY=dev-secret-key-not-for-production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=studymate_dev
      - POSTGRES_USER=studymate
      - POSTGRES_PASSWORD=dev123
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CREATE_SUPERUSER=true
    volumes:
      - .:/app  # 코드 변경 시 실시간 반영
      - dev_static_volume:/app/staticfiles
      - dev_media_volume:/app/media
    ports:
      - "8001:8000"  # 포트 충돌 방지
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000

  # Celery 워커 (개발용)
  celery:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: studymate-celery-dev
    command: celery -A studymate_api worker -l debug --concurrency=1
    environment:
      - DJANGO_SETTINGS_MODULE=studymate_api.settings
      - DEBUG=True
      - ENVIRONMENT=development
      - SECRET_KEY=dev-secret-key-not-for-production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=studymate_dev
      - POSTGRES_USER=studymate
      - POSTGRES_PASSWORD=dev123
      - REDIS_URL=redis://redis:6379/1
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - dev_media_volume:/app/media
    depends_on:
      - db
      - redis
    restart: unless-stopped

  # Mailhog (개발용 메일 서버)
  mailhog:
    image: mailhog/mailhog
    container_name: studymate-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  dev_static_volume:
    driver: local
  dev_media_volume:
    driver: local